import type { ModDefinition, TrickDefinition } from './types'

export const MVP_TRICKS: TrickDefinition[] = [
  {
    id: 'ace',
    name: 'Ace',
    family: 'single',
    unlockLevel: 1,
    baseMultiplier: 1,
    masteryUses: 25,
    summary: 'Each die showing 1 scores an extra x1 line.',
  },
  {
    id: 'pair',
    name: 'Pair',
    family: 'match',
    unlockLevel: 3,
    baseMultiplier: 1.25,
    masteryUses: 25,
    summary: 'Best pair in the roll scores once.',
  },
  {
    id: 'threeKind',
    name: '3-Kind',
    family: 'set',
    unlockLevel: 5,
    baseMultiplier: 2,
    masteryUses: 25,
    summary: 'Best three-of-a-kind scores once.',
  },
  {
    id: 'streak3',
    name: 'Streak 3',
    family: 'streak',
    unlockLevel: 7,
    baseMultiplier: 1.5,
    masteryUses: 25,
    summary: 'Three unique consecutive faces score once.',
  },
  {
    id: 'twoPair',
    name: 'Two Pair',
    family: 'match',
    unlockLevel: 9,
    baseMultiplier: 1.75,
    masteryUses: 25,
    summary: 'Two distinct pairs score one line together.',
  },
  {
    id: 'fullHouse',
    name: 'Full House',
    family: 'set',
    unlockLevel: 11,
    baseMultiplier: 3,
    masteryUses: 25,
    summary: 'A triple plus a pair scores once.',
  },
  {
    id: 'fourKind',
    name: '4-Kind',
    family: 'set',
    unlockLevel: 13,
    baseMultiplier: 3.5,
    masteryUses: 25,
    summary: 'Best four-of-a-kind scores once.',
  },
  {
    id: 'streak4',
    name: 'Streak 4',
    family: 'streak',
    unlockLevel: 15,
    baseMultiplier: 2.5,
    masteryUses: 25,
    summary: 'Four unique consecutive faces score once.',
  },
  {
    id: 'fiveKindPlus',
    name: '5-Kind+',
    family: 'set',
    unlockLevel: 17,
    baseMultiplier: 5.5,
    masteryUses: 25,
    summary: 'Five or more matching dice scale beyond the base tier.',
  },
  {
    id: 'streak5Plus',
    name: 'Streak 5+',
    family: 'streak',
    unlockLevel: 19,
    baseMultiplier: 4,
    masteryUses: 25,
    summary: 'Five or more unique consecutive faces scale beyond the base tier.',
  },
]

export const MVP_MOD_POOL: ModDefinition[] = [
  {
    id: 'selfMult',
    name: 'Self Mult',
    baseValue: 0.25,
    isPerTurnStacking: true,
    summary: 'Adds +25% die mult per rank each turn to this die.',
  },
  {
    id: 'allDiceMult',
    name: 'All-Dice Mult',
    baseValue: 0.01,
    isPerTurnStacking: true,
    summary: 'Adds +1% die mult per rank each turn to every die.',
  },
  {
    id: 'extraMoney',
    name: 'Extra Money',
    baseValue: 1,
    isPerTurnStacking: false,
    summary: 'Adds +100% of face per rank as extra money output.',
  },
  {
    id: 'extraXp',
    name: 'Extra XP',
    baseValue: 1,
    isPerTurnStacking: false,
    summary: 'Adds +100% of face per rank as extra XP output.',
  },
  {
    id: 'extraTurnPoints',
    name: 'Extra Turn Points',
    baseValue: 1,
    isPerTurnStacking: false,
    summary: 'Adds +100% of face per rank as extra turn point output.',
  },
]
